# Generated by Django 2.2.1 on 2019-09-25 05:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50, unique=True)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Name', models.CharField(max_length=50)),
                ('Description', models.CharField(default='DEFAULT DESCRIPTION', max_length=500)),
                ('N_to', models.IntegerField(default=0)),
                ('S_to', models.IntegerField(default=0)),
                ('E_to', models.IntegerField(default=0)),
                ('W_to', models.IntegerField(default=0)),
                ('Item', models.ManyToManyField(blank=True, to='mud5games.Items')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('currentRoom', models.IntegerField(default=0)),
                ('the_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mud5games.User')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='Room',
            field=models.ManyToManyField(blank=True, to='mud5games.Rooms'),
        ),
    ]
