# Generated by Django 2.2.1 on 2019-09-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mud5games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Name', models.CharField(max_length=50)),
                ('Item', models.ManyToManyField(blank=True, to='mud5games.Items')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50, unique=True)),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Token', models.CharField(max_length=100, null=True)),
                ('Item', models.ManyToManyField(blank=True, to='mud5games.Items')),
                ('Room', models.ManyToManyField(blank=True, to='mud5games.Rooms')),
            ],
        ),
        migrations.DeleteModel(
            name='Players',
        ),
        migrations.AddField(
            model_name='items',
            name='Room',
            field=models.ManyToManyField(blank=True, to='mud5games.Rooms'),
        ),
    ]
